<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "document_storage"
 *
 * Auto generated by Extension Builder 2019-03-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'Document Storage',
    'description'      => '',
    'category'         => 'services',
    'author'           => 'Daniel Corn',
    'author_email'     => 'info@cundd.net',
    'state'            => 'alpha',
    'clearCacheOnLoad' => false,
    'version'          => '1.0.0',
    'constraints'      => [
        'depends'   => [
            'typo3' => '11.5-12.4.99',
        ],
        'conflicts' => [],
        'suggests'  => [],
    ],
];
